import { EPetGender, EPetType } from "../enums/pet.enum";
import { IPetDetail } from "../interfaces/pet.interface";

export const LIST_PET: Array<IPetDetail> = [
  {
    petType: EPetType.CAT,
    avatarUrl:
      "https://static.chotot.com/storage/chotot-kinhnghiem/c2c/2019/10/gia-cua-meo-anh-long-ngan-2.jpg",
    avatarAlt: "Cat 1",
    name: "Leo",
    dob: "2023-06-15",
    gender: EPetGender.MALE,
    weigh: 4.5,
    vaccination: 2,
    picture: 10,
    calendar: 3,
    log: 5,
    owner: 1,
  },
  {
    petType: EPetType.DOG,
    avatarUrl: "",
    avatarAlt: "Dog 1",
    name: "Buddy",
    dob: "2022-04-20",
    gender: EPetGender.MALE,
    weigh: 12.0,
    vaccination: 5,
    picture: 15,
    calendar: 2,
    log: 8,
    owner: 2,
  },
  {
    petType: EPetType.CAT,
    avatarUrl: "",
    avatarAlt: "Cat 2",
    name: "Milo",
    dob: "2023-01-10",
    gender: EPetGender.FEMALE,
    weigh: 3.8,
    vaccination: 3,
    picture: 8,
    calendar: 4,
    log: 6,
    owner: 1,
  },
  {
    petType: EPetType.DOG,
    avatarUrl: "",
    avatarAlt: "Dog 2",
    name: "Max",
    dob: "2021-12-05",
    gender: EPetGender.MALE,
    weigh: 18.5,
    vaccination: 6,
    picture: 20,
    calendar: 5,
    log: 10,
    owner: 3,
  },
  {
    petType: EPetType.CAT,
    avatarUrl: "",
    avatarAlt: "Cat 3",
    name: "Luna",
    dob: "2023-03-22",
    gender: EPetGender.FEMALE,
    weigh: 4.2,
    vaccination: 4,
    picture: 12,
    calendar: 2,
    log: 7,
    owner: 4,
  },
];
